### ISSUE TITLE
Unable to install with pip, PIPY is broken

### ISSUE THREAD

**Issue by vietnguyengit** [xarray-contrib/xncml#20]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `conda list` of the conda environment you are using
- [x] Minimal, self-contained copy-pastable example that generates the issue if possible. Please be concise with code posted. See guidelines below on how to provide a good bug report:

     -  [Minimal Complete Verifiable Examples](https://stackoverflow.com/help/mcve)
    -  [Craft Minimal Bug Reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

    Bug reports that follow these guidelines are easier to diagnose,
    and so are often handled much more quickly.

### Description

Unable to install with `pip`

### What I Did

Ran a typical `pip install` command as instructed

![image](https://user-images.githubusercontent.com/26201635/203790399-e84cd741-9cba-4393-aa29-f6c52f58e20f.png)

It turns out that something's broken in `PYPI`
![image](https://user-images.githubusercontent.com/26201635/203790192-2adf02c3-31c7-41c0-96d9-40bf060cd063.png)

**Comment by huard** [comment]
v0.1 was just not released yet. 

Should be fixed now.
