### ISSUE TITLE
Opening ncml files similarly to loadeR in R

### ISSUE THREAD

**Issue by RSO9192** [xarray-contrib/xncml#52]
### Description
We currently developed [a library](https://risk-team.github.io/CAVAanalytics/) that streamlines access and processing of CORDEX-CORE models (among other things).
We would like to make this data available to the Python community as well. 

In R, the [loadR package](https://github.com/SantanderMetGroup/loadeR) allows you to easily read and open ncml files. Below is an example that you can reproduce if you install loadeR.
```
library(loadeR)
url_ncml = "https://data.meteo.unican.es/thredds/dodsC/fao/interp025/aggregations/CORDEX/output/AFR-22/GERICS/MOHC-HadGEM2-ES/historical/r1i1p1/REMO2015/v1/day/CORDEX_output_AFR-22_GERICS_MOHC-HadGEM2-ES_historical_r1i1p1_REMO2015_v1_day.ncml"

data = loadGridData(dataset = url_ncml, var = "pr", season = 1:12, years = 1980, lonLim = c(0,5), latLim = c(0,5))

```
Is there anything equivalent to this in Python? I understand xncml would open ncml files but only if the netCDF files are locally available unless I got this wrong. 

Any suggestions are greatly appreciated!

**Comment by huard** [comment]
Sorry I missed this. 
If the ncml is hosted on a THREDDS server, you'll be able to open it using xarray directly, no need for xncml. 

```
import xarray as xr
ds = xr.open_dataset(url_ncml)
```
