### ISSUE TITLE
Outdated xsd

### ISSUE THREAD

**Issue by bzah** [xarray-contrib/xncml#61]
It looks like the xsd (XML Schema Definition) at `schemas/ncm-2-2.xsd` is outdated.

For example, there are missing types such as the unsigned integers, that would be needed for me.

I believe the latest version of the xsd can be fetched from netCDf-java directly here https://github.com/Unidata/netcdf-java/blob/maint-5.x/cdm/core/src/main/resources/resources/nj22/schemas/ncml-2.2.xsd#L4

Are you interested in updating the schema and if so, how could I generate again the modules in `generated/ ` ?

Note
----
I have also opened an issue on netcdf-java to make sure ncml doc is updated: https://github.com/Unidata/netcdf-java/issues/1271

**Comment by huard** [comment]
Yes, I'd welcome a PR for this. 

I used https://pypi.org/project/xsdata/  to generate the classes if I recall correctly.
