### ISSUE TITLE
Feature request: Create a Datatree instead of a Dataset when there are groups

### ISSUE THREAD

**Issue by bzah** [xarray-contrib/xncml#64]
Feature request
----------------

When I open a ncml that contains groups and sub-groups, the result is flatten: each variable is added to a single "root" Dataset and the initial hierarchy is lost.
This behavior is different from `xarray open_dataset()` which will only open the root group (but not subgroups) and, given the `group="/data"` kwarg, would only open the group "/data".

It would be nice if we could keep the hierarchy in either a DataArray `encoding` property (like the parent group path of the variable) or, even better, to output a Datatree which would contain all groups and subgroups.

Or should we wait until [datatree is merged into xarray ](https://github.com/pydata/xarray/issues/8572) before considering this feature ?

Ref
---

- datatree : https://github.com/xarray-contrib/datatree
- open_dataset doc: https://docs.xarray.dev/en/stable/generated/xarray.open_dataset.html

**Comment by huard** [comment]
My objective is for `open_ncml` to behave as much as possible as `open_dataset`. 

I don't think I've ever used netCDF groups, so I'll defer to your judgement regarding implementation.
