### ISSUE TITLE
Update documentation with new `open_ncml` content

### ISSUE THREAD

**Issue by huard** [xarray-contrib/xncml#8]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion

### Description

- The docs should include some info on the `open_ncml` function. 
- Change github organization link to xarray-contrib in the docs

**Comment by andersy005** [comment]
@huard, i'm curious... what are your thoughts on switching to markdown and using https://myst-parser.readthedocs.io/en/latest/ for documentation authoring? I've found myst + markdown to provide a much better user experience than Restructured Text....

**Comment by huard** [comment]
@andersy005 I had exactly the same idea. Let's do this. 

I'll open a new ticket for this and then suggest we issue a 0.1 release.
